#!/bin/bash
set -x
rm -fr microservices-workshop-billing
git clone https://github.com/tyrion70/microservices-workshop-billing.git
cd microservices-workshop-billing
echo "Starting testing service with port 10010"

# Lock it
touch services/10010.lock

# Get IP
ip=`ifconfig en0|grep inet\  |awk -F\  '{print $2}'`

# Change in case of other consul
consulip=${ip}
# consulip=10.240.107.138

# Run it
PS=`docker run -d -p 10010:80 -e "NAME=10010" -e "CONSULURL=${consulip}:8500" -t billing|cut -c1-12`
echo $PS >services/10010.lock

newman -c Billing.postman_collection

docker kill $PS