#!/bin/bash
set -x
rm -fr microservices-workshop-billing
git clone https://github.com/tyrion70/microservices-workshop-billing.git
cd microservices-workshop-billing
firstavail=`find services -type f -exec basename {} \;|grep -v lock|sort|head -1`
if [ $firstavail == "" ]
then
  echo "No service available"
fi
echo "Starting service with port $firstavail"

# Lock it
mv services/$firstavail services/$firstavail.lock

# Get IP
ip=`ifconfig en0|grep inet\  |awk -F\  '{print $2}'`

# Change in case of other consul
consulip=${ip}
# consulip=10.240.107.138

# Run it
PS=`docker run -d -p 10010:80 -e "NAME=10010" -e "CONSULURL=${consulip}:8500" -t billing|cut -c1-12`
echo $PS >services/10010.lock

# Don't register it! We don't want it to run live yet
#data=`cat billing.json | sed "s/##PORT##/$firstavail/" | sed "s/##DOCKER##/$PS/" | sed "s/##IP##/$ip/"`
#echo $data > consulconfig/$firstavail.json
#consul reload -rpc-addr $ip:8400
#curl -X PUT http://localhost:8500/v1/agent/service/register --data "$data"

newman -c Billing.postman_collection

docker kill $PS
./housekeeping